#!/usr/bin/env python
import sys
sys.path.append('../src/lightkurve')
from lightkurve import KeplerTargetPixelFile
import argparse
sys.path.append('../K2tools')
from utils import *

parser = argparse.ArgumentParser(description="""
                create aperture mask given radius and/or shape""",
                usage='use "%(prog)s --help" for more information',
                formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('f', help='tpf filename', type=str)
parser.add_argument('--r', help='aperture radius in pixels (default=4)', default=4, type=int)
parser.add_argument('--m', help='aperture mask shape [round|square|irregular] (default=round)',default='round', type=str)
parser.add_argument('-s', help='show plot with mask', action='store_true', default=False)

args = parser.parse_args()
fname = args.f
mask  = args.m
rad   = args.r
showfig = args.s

tpf = KeplerTargetPixelFile(fname, quality_bitmask='hardest')
fluxes = tpf.flux
make_mask(fluxes, shape=mask, rad=rad, showfig=showfig);
